### ISSUE TITLE
Questions on Building with pure CMake 

### ISSUE THREAD

**Issue by SamChenzx** [ChristophTobler/snap_cam#1]
According to Snapdragon: Camera driver, Building with pure CMake, when I run cmake ..
it returns "Could not find camera libraries, not building targets that depend on it" ,is that mean I need to install some other packages to run it properly?
root@ubuntu:~/src/snap_cam/build# cmake ..
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building snap_cam without catkin
-- Building klt_feature_tracker without catkin
CMake Warning at CMakeLists.txt:59 (message):
  Could not find camera libraries, not building targets that depend on it

-- Configuring done
-- Generating done
-- Build files have been written to: /root/src/snap_cam/build

and when I run make after this, get the follow:

root@ubuntu:~/src/snap_cam/build# make
Scanning dependencies of target klt_feature_tracker
[ 50%] Building CXX object build/CMakeFiles/klt_feature_tracker.dir/src/trackFeatures.cpp.o
[100%] Linking CXX static library libklt_feature_tracker.a
[100%] Built target klt_feature_tracker

**Comment by ChristophTobler** [comment]
@SamChenzx Are You building on a Snapdragon Flight? This means that the library for the camera was not found (should be standard on a Snapdragon). Can you try to locate the library on your Snapdragon (e.g. locate libcamera.so)?

**Comment by SamChenzx** [comment]
@ChristophTobler 
Thanks for your reply, I used to pull and build it on Ubuntu Desktop, and assume to install it to snapdragon by adb push. So, as for the ROS staff, should it be deployed on Snapdragon Flight as well?

**Comment by ChristophTobler** [comment]
@SamChenzx All the instructions need to be done on the snapdragon side. You only need the snap_cam repo on your Desktop Computer for the calibration

**Comment by SamChenzx** [comment]
Thanks, I'll try it.
